Change form component
AlvinMax/jupyterlab-git pull request #2
Opened 2021-08-09 12:26 UTC by GermanVor

Не стал делать display: none для кнопок диалога, чтобы не вмешиваться в чужую библиотеку, поэтому приходится хранить промежуточные состояния компонента и делать валидацию за его пределами.

2021-08-09 14:37 UTC, teleginzhenya requested changes

2021-08-09 14:37 UTC, teleginzhenya commented on package.json
> +    "build": "tsc",
Давай тут вернём `jlpm install && tsc`, вдруг это как-то используется

2021-08-09 14:37 UTC, teleginzhenya commented on src/commonData/components.tsx
> +const SecretsDropDownList = React.forwardRef<
А `ref` используется, не вижу, чтобы он был прокинут?

2021-08-09 14:37 UTC, teleginzhenya commented on src/commonData/components.tsx
> +            className="jp-mod-styled s3-form__select"
Тут бы лучше на завязываться на `s3-form__select`, попробуй `.datasphere-select`, может он подойдет https://nda.ya.ru/t/TBclnPkO48xdji

2021-08-09 14:37 UTC, teleginzhenya commented on src/commonData/components.tsx
> +    <div className={`lm-Widget p-Widget jp-Spinner ${className}`} tabIndex={-1}>
А зачем `tabIndex`, див же не должен навигироваться табом?

2021-08-09 14:43 UTC, GermanVor commented on src/commonData/components.tsx
> +    <div className={`lm-Widget p-Widget jp-Spinner ${className}`} tabIndex={-1}>
он из коробки был
Уберу

2021-08-11 14:47 UTC, teleginzhenya commented
https://nda.ya.ru/t/q9N8is0b49HHJM

2021-08-11 14:47 UTC, closed without merging